//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtest01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trytryEntities : DbContext
    {
        public trytryEntities()
            : base("name=trytryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Customer_Favorite> Customer_Favorite { get; set; }
        public virtual DbSet<Message_Board> Message_Board { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<Store_Business> Store_Business { get; set; }
        public virtual DbSet<Store_Products> Store_Products { get; set; }
    }
}
