//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtest01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Business
    {
        public int StoreID { get; set; }
        public int CalendarID { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string Address_City { get; set; }
        public string Address_Local { get; set; }
        public string Store_Address { get; set; }
        public byte[] Punch_day { get; set; }
        public string Punch_Start { get; set; }
        public string Punch_End { get; set; }
        public Nullable<bool> OnBusiness { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Store Store { get; set; }
    }
}
